name: MacOS build
on:
    release:
        types: [published]

jobs:
    build:
        name: Build
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: 1.49.0
                  target: x86_64-apple-darwin
                  override: true

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --target x86_64-apple-darwin --release

            - name: Release
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: target/x86_64-apple-darwin/release/wf2
                  asset_name: wf2
                  asset_content_type: application/octet-stream
